### ISSUE TITLE
Model training each time the swap is run

### ISSUE THREAD

**Issue by joacotornello** [eric-ai-lab/swap-anything#3]
Hi, I'm not entirely sure if this is a expected o not, but each time I run
`python main.py --config config_personal_swap.yml`
the model linked in the configuration starts to train for an amount of epochs (200, 500, depending on the **total_diffusion_steps** value setting).  This is _before_ actually doing the swapping (inference).

I didn't debug the code so I'm not 100% sure the model is training during that process, but it looks like it is. 
Is it expected, to take 10-12 minutes to do a swap, or it should take around the same amount of time as a img2img/inpainting SD process?

**Comment by g-jing** [comment]
A 10-minute duration seems unusual. For each image-source-prompt pair, we first need to perform null text inversion with DDIM to obtain the inverted latent, but that process only takes about a minute. This latent result can then be reused for all parameter swaps.

In the default configuration file, there are 10 swapping groups, each taking roughly 5 seconds. So, the total swapping time should be around 50 seconds, bringing the overall process to approximately 2 minutes.

1. If you're aware of the optimal self-attention and cross-attention ranges, you can directly apply those settings. The default setup, however, uses grid search to explore different hyperparameters for editing.
2. You can modify the code to save the uncond_embedding (see https://github.com/eric-ai-lab/swap-anything/blob/306984fb31dd7ccd20098081b231428cdb0f91d4/main.py#L994C26-L994C43), which would eliminate the need to recalculate it for the same source image and source prompt combination.
3. Some papers suggest methods to directly estimate the uncond_embedding, which is much faster. I may implement these methods in the future, though not immediately.
